[project]
authors = ["Misha Mikhasenko <mikhail.mikhasenko@gmail.com>"]
channels = ["conda-forge"]
description = "Educational materials for the K-matrix formalism in the field of hadron physics"
name = "kmatrix-day-2024"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[dependencies]
ampform = "*"
ipympl = "*"
ipywidgets = "*"
juliaup = "*"
jupyterlab = "*"
jupyterlab-git = "*"
jupyterlab-lsp = "*"
jupyterlab-myst = "*"
matplotlib = "*"
myst-nb = "*"
nbstripout = "*"
plotly = "*"
python = "*"
python-lsp-server = "*"
sphinx-autobuild = "*"
sphinx-book-theme = "*"
sphinx-codeautolink = "*"
sphinx-copybutton = "*"
sphinx-design = "*"
sympy = "*"
taplo = "*"

[tasks.doc]
cmd = """
sphinx-build \
    --keep-going \
    -TW \
    -b html \
    docs/ docs/_build/html
"""

[tasks.doclive]
cmd = """
sphinx-autobuild \
    --open-browser \
    --re-ignore '.*/.ipynb_checkpoints/.*' \
    --re-ignore 'docs/_build/.*' \
    --re-ignore 'docs/_static/.*' \
    --watch docs \
    docs/ docs/_build/html
"""

[tasks.doc-julia]
cmd = """
julia --project=.. -e 'using PlutoSliderServer; PlutoSliderServer.export_notebook("K-matrix.jl")'
"""
cwd = "docs"
depends-on = [
    "install-julia",
]

[tasks.install-julia]
cmd = """
juliaup add 1.11.4 && \
juliaup default 1.11.4 && \
julia --project -e 'using Pkg; Pkg.instantiate()'
"""

[tasks.lab]
cmd = "jupyter lab docs"

[tasks.lint]
cmd = """
nbstripout docs/*.ipynb && \
taplo format
"""

[tasks.pluto]
cmd = """
julia --project -e 'using Pluto; Pluto.run(notebook="docs/K-matrix.jl")'
"""
depends-on = [
    "install-julia",
]
